### ISSUE TITLE
[BUG] Inconsistent Website Card Spacing

### ISSUE THREAD

**Issue by dubeyanant** [dubeyanant/Curations#2]
**Describe the bug**
There is an inconsistency in the gap between website cards on the screen. The gaps between the cards are not uniform, leading to a visually unappealing layout.

**To Reproduce**

1. Go to the home page.
2. Click on website tab.
3. Observe the varying gaps between the cards.

**Expected behavior**
The gap between website cards should be uniform, providing a visually consistent and appealing layout.

**Screenshots**
![issue](https://github.com/dubeyanant/Curations/assets/93765660/f957e934-3eac-4a49-a71e-991ca872822d)

**Comment by maazshakeel** [comment]
@dubeyanant  I'd like to work on this issue, can I be assigned?

**Comment by dubeyanant** [comment]
Sure! @maazshakeel Simply read [README.md](https://github.com/dubeyanant/Curations/blob/main/README.md) and [CONTRIBUTING.md](https://github.com/dubeyanant/Curations/blob/main/CONTRIBUTING.md) before you begin working on this issue. Make sure the spacing is responsive. Also, it would be fantastic if you could make the quotes section card spacing responsive as it follows the same principles.

**Comment by maazshakeel** [comment]
Great, I'll start working on it!

**Comment by dubeyanant** [comment]
Hey @maazshakeel You can also look at this [Figma](https://www.figma.com/file/ZpLuGbcAo7YNKoF5qxZp7D/Screen?type=design&node-id=0-1&mode=design) file to get a sense of spacing and everything else related to it.

**Comment by maazshakeel** [comment]
Ok, great! Actually, Why the screen is blank:
![image](https://github.com/dubeyanant/Curations/assets/62890173/580c22da-36a2-4a5e-af65-034b9a9c7cf8)

**Comment by dubeyanant** [comment]
Have you followed [these](https://github.com/dubeyanant/Curations/blob/main/CONTRIBUTING.md#development-setup) steps?

**Comment by maazshakeel** [comment]
Sorry, hold on!

**Comment by maazshakeel** [comment]
Got it, my bad :sweat_smile: 

![image](https://github.com/dubeyanant/Curations/assets/62890173/9a52084b-14ce-4e56-8c7a-2fd3e254ead0)

**Comment by maazshakeel** [comment]
I'm sorry @dubeyanant, I've got some (freelance) work to do, therefore I wouldn't be able to work on this issue.

**Comment by dubeyanant** [comment]
No issues @maazshakeel (●'◡'●)
And all the best for your freelance work!
